POST http://localhost:4004/odata/v4/music/RepairIncidents(05ca551d-5830-496f-9571-fe1d28d1737d)/assignTechnician
Content-Type: application/json

{
  "employeeID": "16949689-b7ff-46bb-bb33-ef538f1e1b9f"
}



GET http://localhost:4004/odata/v4/HR/Employees
